### PR TITLE
LIT-278 check return value and handle more errors when calling he_internal_renegotiate_ssl

### PR DESCRIPTION
**Pull request by expressvpn-tom-l**
## Description
Check return value and handle more errors when calling he_internal_renegotiate_ssl.

Introduced a new `HE_ERR_SECURE_RENEGOTIATION_ERROR` error code. This error is non-fatal.

## Motivation and Context
wolfSSL_Rehandshake may return SECURE_RENEGOTIATION_E but it wasn't handled before. 
The return value of he_internal_renegotiate_ssl was also ignored which might hide some issues.
Exposing and handling more errors so that we can add server metrics.

## How Has This Been Tested?
CI tested.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All active GitHub checks are passing  
- [x] The correct base branch is being used, if not `main`

### CODE REVIEW

**Comment by kp-mariappan-ramasamy** [comment]
@expressvpn-tom-l A couple of questions

>  Introduced a new HE_ERR_SECURE_RENEGOTIATION_ERROR error code. This is a fatal error and a client/server implementation should disconnect the connection if it gets this error during DTLS 1.2 secure renegotiation.

1. I have taken a quick look at  [documentation](https://www.wolfssl.com/doxygen/group__IO.html#ga7ba02472014a68d0717ca9243d9dd646) and it did not mention that `SECURE_RENEGOTIATION_E` was a fatal error. 

Is this something we found from testing or looking through the implementation ?


2. Was this error happened with only one of the connection or it happened with all DTLS1.2 connections ?
3. Is this reproducible in local setup ?

**Comment by expressvpn-tom-l** [comment]
> I have taken a quick look at [documentation](https://www.wolfssl.com/doxygen/group__IO.html#ga7ba02472014a68d0717ca9243d9dd646) and it did not mention that SECURE_RENEGOTIATION_E was a fatal error.

Good point. I looked at WolfSSL source: https://github.com/wolfSSL/wolfssl/blob/master/src/ssl.c#L4003-L4053, there are 5 cases it may return SECURE_RENEGOTIATION_E error. None of them seems fatal to me now, so I'll change it to non-fatal in next commit.

**Comment by expressvpn-tom-l** [comment]
> Is this something we found from testing

No, I cannot reproduce this error in local testing. Also, because we previously ignored these errors, we don't know if it ever happens in production. Handling and exposing more errors allow us adding metrics to monitoring it.

**Review by kp-mariappan-ramasamy — APPROVED** [review]
LGTM

**Pull request merged**
